//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string item_uid { get; set; }
        public string user_uid { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> item_price { get; set; }
        public string group_uid { get; set; }
        public bool crossed_off { get; set; }
    
        public virtual user user { get; set; }
    }
}
